CREATE TABLE IF NOT EXISTS `alumni` (
  `id_alumni` int(11) NOT NULL AUTO_INCREMENT,
  `id_siswa_asal` int(11) DEFAULT NULL,
  `nama_siswa` varchar(150) NOT NULL,
  `nisn` varchar(30) DEFAULT NULL,
  `nipd` varchar(30) DEFAULT NULL,
  `nik` varchar(30) DEFAULT NULL,
  `no_kk` varchar(30) DEFAULT NULL,
  `jenis_kelamin` varchar(20) DEFAULT NULL,
  `tempat_lahir` varchar(100) DEFAULT NULL,
  `tanggal_lahir` date DEFAULT NULL,
  `agama` varchar(30) DEFAULT NULL,
  `telepon` varchar(30) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `rombel` varchar(100) DEFAULT NULL,
  `tanggal_pendaftaran` date DEFAULT NULL,
  `status_pendaftaran` varchar(100) DEFAULT NULL,
  `status_keaktifan` varchar(30) DEFAULT 'Aktif',
  `status_alumni` varchar(30) DEFAULT NULL,
  `tanggal_alumni` date DEFAULT NULL,
  `sekolah_terakhir` varchar(150) DEFAULT NULL,
  `rombel_terakhir` varchar(150) DEFAULT NULL,
  `created_from_siswa_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `no_ijazah` varchar(100) DEFAULT NULL,
  `kewarganegaraan` varchar(50) DEFAULT 'Indonesia',
  `anak_ke` int(3) DEFAULT NULL,
  `alamat` text,
  `rt` varchar(5) DEFAULT NULL,
  `rw` varchar(5) DEFAULT NULL,
  `jenis_tempat_tinggal` varchar(100) DEFAULT NULL,
  `alat_transportasi` varchar(100) DEFAULT NULL,
  `jarak_ke_sekolah` varchar(100) DEFAULT NULL,
  `koordinat` varchar(100) DEFAULT NULL,
  `sekolah_asal` varchar(150) DEFAULT NULL,
  `riwayat_penyakit` text,
  `prestasi_siswa` text,
  `id_provinsi` varchar(20) DEFAULT NULL,
  `id_kabupaten` varchar(20) DEFAULT NULL,
  `id_kecamatan` varchar(20) DEFAULT NULL,
  `id_kelurahan` varchar(20) DEFAULT NULL,
  `nama_ayah` varchar(150) DEFAULT NULL,
  `nik_ayah` varchar(30) DEFAULT NULL,
  `pekerjaan_ayah` varchar(100) DEFAULT NULL,
  `penghasilan_ayah` varchar(100) DEFAULT NULL,
  `tahun_lahir_ayah` year(4) DEFAULT NULL,
  `pendidikan_ayah` varchar(100) DEFAULT NULL,
  `alamat_ayah_sama_siswa` tinyint(1) NOT NULL DEFAULT '0',
  `alamat_ayah` text,
  `id_provinsi_ayah` varchar(20) DEFAULT NULL,
  `id_kabupaten_ayah` varchar(20) DEFAULT NULL,
  `id_kecamatan_ayah` varchar(20) DEFAULT NULL,
  `id_kelurahan_ayah` varchar(20) DEFAULT NULL,
  `nama_ibu` varchar(150) DEFAULT NULL,
  `nik_ibu` varchar(30) DEFAULT NULL,
  `pekerjaan_ibu` varchar(100) DEFAULT NULL,
  `penghasilan_ibu` varchar(100) DEFAULT NULL,
  `tahun_lahir_ibu` year(4) DEFAULT NULL,
  `pendidikan_ibu` varchar(100) DEFAULT NULL,
  `alamat_ibu_sama_siswa` tinyint(1) NOT NULL DEFAULT '0',
  `alamat_ibu` text,
  `id_provinsi_ibu` varchar(20) DEFAULT NULL,
  `id_kabupaten_ibu` varchar(20) DEFAULT NULL,
  `id_kecamatan_ibu` varchar(20) DEFAULT NULL,
  `id_kelurahan_ibu` varchar(20) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_alumni`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `alumni_foto` (
  `id_foto_alumni` int(11) NOT NULL AUTO_INCREMENT,
  `id_alumni` int(11) NOT NULL,
  `id_foto_asal` int(11) DEFAULT NULL,
  `foto` varchar(255) NOT NULL,
  `label` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id_foto_alumni`),
  KEY `idx_alumni_foto_id_alumni` (`id_alumni`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `alumni_dokumen` (
  `id_dokumen_alumni` int(11) NOT NULL AUTO_INCREMENT,
  `id_alumni` int(11) NOT NULL,
  `id_dokumen_asal` int(11) DEFAULT NULL,
  `id_jenis_dokumen` int(11) DEFAULT NULL,
  `nomor_dokumen` varchar(100) DEFAULT NULL,
  `tanggal_dokumen` date DEFAULT NULL,
  `berkas` varchar(255) DEFAULT NULL,
  `keterangan` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id_dokumen_alumni`),
  KEY `idx_alumni_dokumen_id_alumni` (`id_alumni`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `alumni_pembelajaran_siswa` (
  `id_alumni_pembelajaran_siswa` int(11) NOT NULL AUTO_INCREMENT,
  `id_pembelajaran` int(11) NOT NULL,
  `id_alumni` varchar(100) NOT NULL,
  `id_siswa_asal` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_alumni_pembelajaran_siswa`),
  KEY `idx_alumni_pembelajaran_id_pembelajaran` (`id_pembelajaran`),
  KEY `idx_alumni_pembelajaran_id_alumni` (`id_alumni`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `alumni_nilai_siswa` (
  `id_alumni_nilai_siswa` int(11) NOT NULL AUTO_INCREMENT,
  `id_pembelajaran_mapel` int(11) NOT NULL,
  `id_alumni` int(11) NOT NULL,
  `id_siswa_asal` int(11) DEFAULT NULL,
  `nilai_harian` decimal(5,2) DEFAULT NULL,
  `nilai_psts` decimal(5,2) DEFAULT NULL,
  `nilai_psas` decimal(5,2) DEFAULT NULL,
  `nilai_rapor` decimal(5,2) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id_alumni_nilai_siswa`),
  KEY `idx_alumni_nilai_id_pembelajaran_mapel` (`id_pembelajaran_mapel`),
  KEY `idx_alumni_nilai_id_alumni` (`id_alumni`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
